import Foundation

/// Role of a message in a chat conversation.
public nonisolated enum ChatRole: String, Sendable, Codable, Equatable {
    case system = "system"
    case user = "user"
    case assistant = "assistant"
    case tool = "tool"
}

/// A structured tool call request generated by a model.
public nonisolated struct ToolCall: Sendable, Codable, Equatable, Identifiable {
    public let id: String
    public let name: String
    public let arguments: String // JSON-encoded arguments string

    public init(id: String = UUID().uuidString, name: String, arguments: String) {
        self.id = id
        self.name = name
        self.arguments = arguments
    }
}

/// The result of executing a tool call, fed back into the harness.
public nonisolated struct ToolResult: Sendable, Codable, Equatable {
    public let callId: String
    public let name: String
    public let content: String

    public init(callId: String, name: String, content: String) {
        self.callId = callId
        self.name = name
        self.content = content
    }
}

/// Definition of a tool exposed to the model.
public nonisolated struct ToolDefinition: Sendable, Codable, Equatable {
    public let name: String
    public let description: String
    public let parametersJSONSchema: String

    public init(name: String, description: String, parametersJSONSchema: String = "{}") {
        self.name = name
        self.description = description
        self.parametersJSONSchema = parametersJSONSchema
    }
}

/// Single message in a chat conversation.
public nonisolated struct ChatMessage: Sendable, Codable, Equatable, Identifiable {
    public let id: UUID
    public let role: ChatRole
    public let content: String
    public let model: String? // For assistant turns: records which model generated this turn
    public let toolCalls: [ToolCall]?
    public let toolCallId: String? // For tool results: references matching ToolCall.id
    public let timestamp: Date

    public init(
        id: UUID = UUID(),
        role: ChatRole,
        content: String,
        model: String? = nil,
        toolCalls: [ToolCall]? = nil,
        toolCallId: String? = nil,
        timestamp: Date = Date()
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.model = model
        self.toolCalls = toolCalls
        self.toolCallId = toolCallId
        self.timestamp = timestamp
    }
}

/// Events yielded during streamed generation.
public nonisolated enum ChatStreamEvent: Sendable, Equatable {
    case token(String)
    case toolCall(ToolCall)
    case turnCompleted(model: String, finishReason: String?)
}

/// Unified async streaming protocol for model backends.
public nonisolated protocol ChatBackend: Sendable {
    var id: String { get }
    var backendType: BackendType { get }

    /// Generate an asynchronous throwing stream of tokens, tool calls, and completion events.
    func generateStream(
        messages: [ChatMessage],
        tools: [ToolDefinition],
        systemPrompt: String?
    ) async throws -> AsyncThrowingStream<ChatStreamEvent, Error>
}

/// Common backend errors.
public nonisolated enum ChatBackendError: LocalizedError, Sendable, Equatable {
    case modelUnavailable(String)
    case connectionFailed(String)
    case invalidResponse(String)
    case contextLengthExceeded(Int)
    case cancelled

    public var errorDescription: String? {
        switch self {
        case .modelUnavailable(let reason):
            return "Model unavailable: \(reason)"
        case .connectionFailed(let reason):
            return "Connection failed: \(reason)"
        case .invalidResponse(let reason):
            return "Invalid response: \(reason)"
        case .contextLengthExceeded(let maxCtx):
            return "Context length exceeded (maximum \(maxCtx) tokens)"
        case .cancelled:
            return "Generation was cancelled"
        }
    }
}
